language: julia

os:
  - linux

julia:
  - 1.2
  - nightly

script:
  - mpichversion
  - julia -e 'using InteractiveUtils;
              versioninfo()'
  # Force precompilation of packages in serial mode.
  # Otherwise, if precompilation runs in parallel, there may be race
  # conditions...
  - julia --project=@. -e 'import Pkg;
                           Pkg.instantiate();
                           using PencilFFTs'
  # Note: code coverage (at least using Coverage.jl) apparently doesn't work
  # with parallel code.
  - julia --project=@. --color=yes -e 'import Pkg; Pkg.test(; coverage=false)'

jobs:
  allow_failures:
    julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

# https://docs.travis-ci.com/user/installing-dependencies/
before_install:
  - sudo apt-get -y install mpich libmpich-dev

addons:
  apt:
    update: true  # runs apt-get update

notifications:
  email: false

# vim: shiftwidth=2
