language: julia

os:
  - linux

julia:
  - 1.2
  - nightly

jobs:
  allow_failures:
    julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

# https://docs.travis-ci.com/user/installing-dependencies/
before_install:
  - sudo apt-get -y install mpich libmpich-dev

addons:
  apt:
    update: true  # runs apt-get update

# vim: shiftwidth=2
