language: julia

os:
  - linux

dist: bionic

julia:
  - 1.3
  - 1.4
  - nightly

env:
  global:
    - JULIA_MPI_BINARY=system

cache:
  directories:
    - $HOME/.julia/registries
    - $HOME/.julia/artifacts

script:
  - julia -e 'using InteractiveUtils;
              versioninfo()'
  # Force precompilation of packages in serial mode.
  # Otherwise, if precompilation runs in parallel, there may be race
  # conditions...
  - julia --project=@. -e 'using Pkg;
                           pkg"instantiate";
                           pkg"precompile";
                           using MPI;
                           println("\n", MPI.MPI_LIBRARY_VERSION_STRING);'
  - julia --project=@. --color=yes -e 'import Pkg; Pkg.test(coverage=true)'

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

# https://docs.travis-ci.com/user/installing-dependencies/
before_install:
  - sudo apt-get -y install mpich libmpich-dev

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; data = process_folder(); Codecov.submit(data); Coveralls.submit(data)'

addons:
  apt:
    update: true  # runs apt-get update

notifications:
  email: false

# vim: shiftwidth=2
